-- Exchange resources: members publish straight to the hub (no approval).
-- Admins (is_admin()) can edit or delete. Run ONCE in Supabase → SQL Editor.
-- Assumes is_admin() already exists (from fix-admin-rls.sql).

create table if not exists public.resources (
  id          bigint generated by default as identity primary key,
  category    text not null default 'Resources'
              check (category in ('Resources','Media briefs','Opportunities')),
  title       text not null,
  meta        text,
  url         text,
  kind        text default 'LINK',
  by          text,
  published   boolean not null default true,
  created_at  timestamptz not null default now()
);

alter table public.resources enable row level security;

-- Anyone can read published resources
drop policy if exists resources_read on public.resources;
create policy resources_read on public.resources
  for select to anon, authenticated
  using (published = true);

-- Anyone can publish a resource (no admin approval) — but only as published,
-- and never as an admin-only field. Keep it to the member-upload shape.
drop policy if exists resources_insert on public.resources;
create policy resources_insert on public.resources
  for insert to anon, authenticated
  with check (published = true);

-- Admins can read everything (incl. anything unpublished) and edit/delete
drop policy if exists resources_admin_all on public.resources;
create policy resources_admin_all on public.resources
  for all to anon, authenticated
  using (is_admin())
  with check (is_admin());

grant select, insert on public.resources to anon, authenticated;
grant update, delete on public.resources to authenticated;
