#!/usr/bin/env bash
# Weekly MazingiraKenya Narrative-Disinfo queue — 2026-10-03
# Queues UNPUBLISHED drafts (published=false) into Supabase disinfo_items for admin review.
# This run wrote the 4 drafts via a connected Chrome (POST /rest/v1/disinfo_items, 201) because
# the Mac device-bridge shell cannot reach supabase.co (proxy 403). This script reproduces the
# same inserts anywhere Supabase IS reachable, via insert-disinfo-draft.mjs.
#   Usage: bash scripts/queue-disinfo-2026-10-03.sh
set -euo pipefail
cd "$(dirname "$0")/.."

node scripts/insert-disinfo-draft.mjs '{"name":"Circulating on social media","posted_at":"2026-10-03","body":"The Earth'\''s temperature has not risen by 1.5°C since 1900 — the warming figures are exaggerated.","verdict":"Climate denial (warming minimised)","verdict_class":"vf","source_url":"https://pesacheck.org/false-the-earths-temperature-did-not-rise-by-1-5-since-1900/","source_label":"PesaCheck · “1.5°C since 1900” fact-check","rebuttal":"Global average surface temperature has risen by roughly 1.3–1.5°C above the pre-industrial (1850–1900) baseline, and 2024 was the first full calendar year to average about 1.5°C above it. Independent records — NASA GISS, NOAA, Berkeley Earth and the UK Met Office/Copernicus — agree to within about a tenth of a degree, drawing on thousands of land stations, ships, buoys and satellites. Because the rise is neither linear nor uniform, cherry-picking a start year or a single cool patch can make it look smaller, but the long-term trend is unambiguous and accelerating. For East Africa the signal is already lived: hotter heatwaves, the near-total loss of ice on Mt Kenya and Kilimanjaro, and sharper swings between drought and flood."}'

node scripts/insert-disinfo-draft.mjs '{"name":"Circulating in carbon-market promotion","posted_at":"2026-10-03","body":"The Northern Kenya Grassland Carbon project is a model climate solution — the world'\''s largest soil-carbon scheme, delivering verified offsets and real benefits to local pastoralist communities.","verdict":"Greenwashing / misleading framing","verdict_class":"vm","source_url":"https://www.survivalinternational.org/news/14571","source_label":"Survival International / REDD-Monitor · Northern Kenya carbon project","rebuttal":"The project — run by the Northern Rangelands Trust and certified by Verra — was marketed as the world'\''s largest soil-carbon removal scheme and sold millions of credits to buyers including Meta and Netflix. But both its climate and community claims are contested. Verra suspended it in 2023 and again in 2025 after a Kenyan court found two conservancies supplying a large share of its credits had been established unconstitutionally, and Maasai and Rendille herders have gone to court alleging they were pressured into agreements restricting traditional grazing without free, prior and informed consent. Scientists have also questioned whether the claimed soil-carbon gains from changed grazing are real and permanent. Verra reinstated the project in June 2026 despite the ongoing case — so presenting a suspended, litigated scheme as a proven, community-benefiting climate solution overstates both its carbon integrity and its local support."}'

node scripts/insert-disinfo-draft.mjs '{"name":"Government climate messaging","posted_at":"2026-10-03","body":"Kenya has planted hundreds of millions of trees toward its 15-billion-tree target — proof the country is reversing deforestation and leading on climate action.","verdict":"Needs context / unverified claim","verdict_class":"vc","source_url":"https://www.kenyans.co.ke/news/127033-environmentalists-pile-pressure-govt-verify-survival-over-981m-trees","source_label":"Kenyans.co.ke · tree-planting verification (Sept 2026)","rebuttal":"Kenya'\''s 15 Billion Trees campaign is real and ambitious, and large numbers of seedlings have been planted. But headline figures — such as the roughly 981 million “tree-growing contributions” logged since 2011 — count trees put in the ground, not trees that survive. Environmentalists including Dr Isaac Kalua Green have pressed the government to return to planting sites and verify how many remain alive, warning that seedlings routinely die from drought, poor maintenance, pests or unsuitable sites and that such losses may not appear in official tallies. Meanwhile the 2023 lifting of the logging moratorium has allowed felling of mature natural forest. Counting seedlings planted as if it equalled restored forest cover, without survival monitoring and independent verification, risks overstating real progress."}'

node scripts/insert-disinfo-draft.mjs '{"name":"Circulating on social media","posted_at":"2026-10-03","body":"El Niño is here — it means guaranteed catastrophic floods across the whole of Kenya in the coming weeks.","verdict":"Needs context / misconception","verdict_class":"vc","source_url":"https://www.kenyans.co.ke/news/125577-kenya-met-releases-el-nino-forecast-says-rains-increase-october-2026","source_label":"Kenya Met (KEMSA) / Kenyans.co.ke · El Niño clarification","rebuttal":"The Kenya Meteorological Department has forecast above-normal October–December 2026 rains and genuine flood risk, so preparedness is warranted. But the service has also had to correct a widespread conflation: “El Niño is not rainfall” — it is a naturally occurring warming pattern in the tropical Pacific that recurs every two to seven years and shifts the odds toward wetter conditions in East Africa, not a guarantee of uniform catastrophic flooding everywhere. Its effects vary by region and timing, and as of early October the department had not yet declared the onset of the rains. Treating “El Niño” as a synonym for certain disaster fuels both panic and the spread of fabricated “forecasts” and evacuation notices; the reliable guidance is the official Kenya Met advisories, not viral posts."}'

echo "Queued 4 disinfo drafts (2026-10-03) — awaiting admin review."
