#!/usr/bin/env bash
# Weekly MazingiraKenya Narrative-Disinfo queue — 2026-09-29
# Queues UNPUBLISHED drafts (published=false) into Supabase disinfo_items for admin review.
# This run wrote the 6 drafts via a connected Chrome (POST /rest/v1/disinfo_items, 201). This
# script reproduces the same inserts anywhere Supabase IS reachable, via insert-disinfo-draft.mjs.
#   Usage: bash scripts/queue-disinfo-2026-09-29.sh
set -euo pipefail
cd "$(dirname "$0")/.."

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on social media", "body": "Sure the ocean is warming, but that'\''s just a natural cycle — it has nothing to do with human emissions.", "verdict": "Climate denial (natural-cause myth)", "verdict_class": "vf", "source_url": "https://pesacheck.org/false-the-heating-of-the-ocean-is-not-natural/", "source_label": "PesaCheck · ocean-warming fact-check", "rebuttal": "The oceans have absorbed more than 90% of the extra heat trapped by human greenhouse-gas emissions, and ocean heat content has climbed to record highs with the rise accelerating since the 1970s — a pattern natural cycles like El Niño or solar variation cannot explain (those would have produced slight cooling over this period). The warming fingerprint, with surface waters heating in step with rising CO₂, points to human causation. For East Africa this is concrete: a warming western Indian Ocean feeds more intense cyclones, coral bleaching along the Kenyan and Tanzanian coast, and the disrupted rainfall tied to the Indian Ocean Dipole."}'

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on social media", "body": "The IPCC itself admits there'\''s no evidence that climate change is affecting extreme weather.", "verdict": "Fabricated / misattributed to IPCC", "verdict_class": "vf", "source_url": "https://pesacheck.org/false-the-ipcc-did-not-say-theres-no-evidence-that-climate-change-is-affecting-extreme-weather/", "source_label": "PesaCheck · IPCC extreme-weather fact-check", "rebuttal": "The IPCC says the opposite. Its Sixth Assessment Report states it is established that human-caused emissions have made heat extremes, heavy rainfall and droughts more frequent and intense in many regions, and that this human influence has strengthened over time. No IPCC report contains the quoted claim; it is a fabrication or a distortion of the reports'\'' careful region-by-region language. East Africa'\''s recent swings between severe multi-season drought and deadly flooding are consistent with exactly the trends the IPCC documents."}'

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on social media", "body": "A new peer-reviewed study proves human emissions have zero impact on the climate.", "verdict": "Climate denial / misrepresented study", "verdict_class": "vf", "source_url": "https://pesacheck.org/false-this-study-does-not-confirm-human-emissions-have-zero-impact-on-climate-change/", "source_label": "PesaCheck · '\''zero impact'\'' study fact-check", "rebuttal": "No credible study shows this. The claim usually rests on a fringe or misrepresented paper whose conclusions the wider evidence does not support, and it ignores several independent lines of proof that human emissions dominate modern warming: CO₂ rising from about 280 ppm before industrialisation to over 420 ppm today, its isotopic signature identifying it as fossil-fuel carbon, and the close match between emissions and observed temperature. Every major national science academy agrees. One contrarian paper does not overturn that body of evidence."}'

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on social media", "body": "Even Bill Gates has now admitted that climate change is a hoax and a lie.", "verdict": "Fabricated quote / false attribution", "verdict_class": "vf", "source_url": "https://pesacheck.org/false-bill-gates-did-not-say-climate-change-is-a-hoax-or-a-lie/", "source_label": "PesaCheck · Bill Gates quote fact-check", "rebuttal": "There is no record of Bill Gates calling climate change a hoax or a lie, and the claim contradicts his long-standing public position — he wrote a book on avoiding climate disaster and funds clean-energy and climate work. Attaching a famous name to a fabricated '\''admission'\'' is a recurring disinformation tactic that makes denial look credible. A supposed quote is only worth repeating if it traces back to a real, verifiable source; this one does not."}'

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on social media", "body": "The physics of the atmosphere'\''s lapse rate proves greenhouse gases can'\''t actually cause warming.", "verdict": "Pseudo-scientific denial", "verdict_class": "vf", "source_url": "https://pesacheck.org/false-this-atmospheric-process-does-not-disprove-the-greenhouse-gas-origin-of-global-warming/", "source_label": "PesaCheck · lapse-rate fact-check", "rebuttal": "The lapse rate — how air cools with altitude — is real physics, but it does not refute the greenhouse effect; the two describe different things. Greenhouse gases such as CO₂ and methane absorb and re-emit outgoing heat, keeping the surface warm enough for life, and adding more of them warms the planet. Studies actually show warming alters the lapse rate, generally reducing it in a feedback that can amplify warming. Presenting a well-understood atmospheric process as if it overturns basic radiative physics is a talking point, not a scientific finding."}'

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on social media", "body": "Magnitude-6 earthquakes are increasing because of climate change.", "verdict": "False attribution / misinformation", "verdict_class": "vf", "source_url": "https://pesacheck.org/false-magnitude-6-earthquakes-are-not-increasing-and-are-not-linked-to-climate-change/", "source_label": "PesaCheck · earthquakes-and-climate fact-check", "rebuttal": "Two things are wrong here. First, the global rate of magnitude-6 earthquakes has not been rising — better instruments record more small quakes, but the frequency of large ones is roughly stable. Second, earthquakes are driven by the movement of tectonic plates deep in the Earth, a process unrelated to atmospheric warming. Blaming quakes on climate change both overstates the data and misassigns the cause, and overstating climate impacts damages public understanding just as denial does. Accurate attribution matters."}'

echo "Queued 6 disinfo drafts (2026-09-29) — awaiting admin review."
