#!/usr/bin/env bash
# Weekly MazingiraKenya Narrative-Disinfo queue — 2026-10-09
# Queues UNPUBLISHED drafts (published=false) into Supabase disinfo_items for admin review.
# This run wrote the 4 drafts via a connected Chrome (POST /rest/v1/disinfo_items, 201) because
# the Mac device-bridge shell cannot reach supabase.co (proxy / HTTP 000). This script reproduces
# the same inserts anywhere Supabase IS reachable, via insert-disinfo-draft.mjs.
#   Usage: bash scripts/queue-disinfo-2026-10-09.sh
set -euo pipefail
cd "$(dirname "$0")/.."

node scripts/insert-disinfo-draft.mjs '{"name":"Circulating on social media","posted_at":"2026-10-09","body":"Scientists are lying about agreement on climate change — only 0.3% of studies actually say humans are causing it, not 97%.","verdict":"Climate denial (consensus denial)","verdict_class":"vf","source_url":"https://pesacheck.org/false-the-scientific-consensus-that-human-activity-causes-climate-change-is-not-just-0-3-per-cent/","source_label":"PesaCheck · climate-consensus fact-check","rebuttal":"The scientific consensus that humans are driving climate change is overwhelming — multiple independent studies put agreement among publishing climate scientists at 97% or higher, and more recent reviews find it above 99%. The “0.3%” figure is a well-worn distortion: it comes from re-slicing a single 2013 survey (Cook et al., which examined ~12,000 abstracts) down to only the few that both explicitly endorsed human causation and quantified it as more than half of warming, then presenting that narrowest sub-category as if it were the whole picture. That same survey found 97% of the papers taking a position endorsed human-caused warming. NASA, NOAA, the IPCC and every major scientific academy agree. Reducing a robust, repeatedly replicated consensus to “0.3%” by cherry-picking one restrictive count is a textbook denial tactic."}'

node scripts/insert-disinfo-draft.mjs '{"name":"Circulating on social media / skeptic blogs","posted_at":"2026-10-09","body":"A peer-reviewed study proves recent warming is caused by the Sun, not CO2 — the CO2–climate link is just an assumption.","verdict":"Climate denial (retracted/misrepresented study)","verdict_class":"vf","source_url":"https://retractionwatch.com/2026/10/02/paper-questioning-co2-and-climate-change-retracted","source_label":"Retraction Watch · CO2 paper retracted (Oct 2026)","rebuttal":"The paper shared as “proof” — a 2023 article by a retired geographer in the MDPI journal Atmosphere — was retracted by the publisher on 16 September 2026 for “unsupported conclusions” and errors in interpreting the data. Reviewers flagged basic factual mistakes, including misnaming the Mauna Loa CO2 observatory as “Mount Kea,” misstating when CO2 measurements began, and dating the Neanderthal extinction to ~3,200 years ago (it was ~40,000). Its core claim — that warming is mainly solar — is a long-debunked talking point: solar output has been flat to slightly declining since the 1980s while temperatures climbed, and the isotopic and seasonal fingerprints of the warming point to fossil CO2, not the Sun. A retracted, error-ridden paper is not evidence, yet it kept circulating (tens of thousands of views and hundreds of social shares) after being withdrawn."}'

node scripts/insert-disinfo-draft.mjs '{"name":"Official forestry messaging","posted_at":"2026-10-09","body":"Reports and viral videos of forest destruction in Kenya are misleading — no public forest has been lost, grabbed or hived off.","verdict":"Misleading framing / minimisation","verdict_class":"vm","source_url":"https://citizen.digital/article/public-outrage-as-viral-videos-reveal-massive-deforestation-in-kenyas-key-water-towers-n391643","source_label":"Citizen Digital · water-tower deforestation footage","rebuttal":"A blanket “nothing has been lost” denial doesn’t match the record. In October 2026, videos geolocated by fact-checkers to Keraita Forest (Kiambu), with others pointing to the Aberdares, showed lorries hauling felled indigenous and mature trees out of gazetted water-tower forest, drawing public outrage and criticism that enforcement weakened after the 2023 lifting of the commercial logging ban. The Kenya Forest Service’s own actions cut against a sweeping denial: it revoked more than 154 irregular forest-land title deeds in 2017 and recently recovered illegally allocated land in Karura Forest with the Ethics and Anti-Corruption Commission — both proof that forest land has in fact been irregularly allocated. Reassuring the public that reports are merely “misleading” while independently located footage shows active logging risks downplaying real, verifiable losses. The accurate response is site-level verification and published permit records, not blanket dismissal."}'

node scripts/insert-disinfo-draft.mjs '{"name":"Circulating in carbon-market promotion","posted_at":"2026-10-09","body":"Soil-carbon projects on Maasai rangelands in northern Tanzania are a win-win — protecting the land, storing carbon and paying communities. A model climate solution for East Africa.","verdict":"Greenwashing / misleading framing","verdict_class":"vm","source_url":"https://www.greenpeace.org/africa/en/blog/60812/when-the-land-speaks-back-tanzanias-maasai-are-rejecting-carbon-credits-on-their-land-the-world-should-pay-attention/","source_label":"Greenpeace Africa · Maasai rangeland carbon credits","rebuttal":"The “win-win” label is contested by the communities themselves. The Longido and Monduli Rangelands Carbon Project — run by Soils for the Future Tanzania with Volkswagen ClimatePartner, covering nearly 970,000 hectares under 40-year contracts — has been challenged by Maasai groups who say contracts were signed without legal advice, translation or proper free, prior and informed consent, and that its fixed 14-day rotational-grazing rules clash with rain-driven herding. Community members filed over 100 objections with the certifier Verra, and reports indicate villages may receive as little as about US$2 per hectare while the resulting credits sell for many times that. The FAO and peer-reviewed research note that dryland soil-carbon gains are highly uncertain and easily reversed by drought or erosion, casting doubt on whether the offsets are real or permanent. Critics call it “carbon colonialism — dispossession with a sustainability logo.” With similar deals reported in Kenya’s Kajiado and Laikipia, presenting a consent-disputed, scientifically shaky scheme as a proven community climate solution overstates both its integrity and its local support."}'

echo "Queued 4 disinfo drafts (2026-10-09) — awaiting admin review."
