#!/usr/bin/env bash
# Events Watch queue — run 2026-09-19 (MazingiraKenya weekly events watcher).
# 9 verified, future-dated (>= 2026-09-19) climate / environmental-justice events
# relevant to Kenya / East Africa / pan-African climate justice.
# These were ALREADY written straight to Supabase as drafts (published=false) on
# 2026-09-19 via the connected-browser write path — all 9 returned HTTP 201.
# This script is the reproducible record; re-running is safe (partial unique index
# calevents_draft_uniq on (title,start_date) returns HTTP 409 for existing drafts).
set -euo pipefail
cd "$(dirname "$0")/.."

node scripts/insert-event-draft.mjs '{"title":"African Symposium on Climate Reparations: Accountability, Equity and Repair","start_date":"2026-09-30","time":"30 Sep – 1 Oct 2026","location":"Mombasa Continental, Shanzu, Mombasa, Kenya","mode":"In person","org":"African Climate Reparations Collective / African Futures Lab","link":"https://www.afalab.org/the-latest/events/2026/african-symposium-on-climate-reparations/","description":"Two-day pan-African forum in Kenya on climate reparations, state obligations and corporate accountability — core to East African climate-justice advocacy."}'
node scripts/insert-event-draft.mjs '{"title":"African Energy Week 2026","start_date":"2026-10-12","time":"12–16 Oct 2026","location":"Cape Town, South Africa","mode":"In person","org":"African Energy Chamber","link":"https://aecweek.com/","description":"Africa flagship energy conference — ministers, financiers and developers debate the continent energy transition; a key fossil-fuel-vs-just-transition arena for climate-justice advocates to track."}'
node scripts/insert-event-draft.mjs '{"title":"Africa Climate Forum (ACF) 2026","start_date":"2026-10-13","time":"13–14 Oct 2026","location":"Shehu Yar Adua Centre, Abuja, Nigeria","mode":"In person","org":"Global Centre for Low-Carbon Business & Enterprise (GCLBE)","link":"https://africaclimateforum.com/","description":"Pan-African forum accelerating climate finance and sustainable growth across Africa — partnerships and commitments on the road to COP31."}'
node scripts/insert-event-draft.mjs '{"title":"CBD COP17 — 2026 UN Biodiversity Conference","start_date":"2026-10-19","time":"19–30 Oct 2026","location":"Yerevan, Armenia","mode":"Hybrid","org":"Convention on Biological Diversity","link":"https://www.cbd.int/conferences/2026","description":"Global biodiversity negotiations and first review of the Kunming-Montreal Framework — bears on African ecosystem protection and nature-based climate solutions."}'
node scripts/insert-event-draft.mjs '{"title":"GreenShift Forum 2026","start_date":"2026-10-22","time":"22 Oct 2026","location":"Nairobi, Kenya","mode":"In person","org":"TechTrends Media & Ardena Consulting","link":"https://techtrendske.co.ke/2026/08/01/nairobi-to-host-esg-leaders-at-greenshift-forum-in-october/","description":"Nairobi ESG, green-finance and carbon-markets forum — practical climate-finance and just-transition angle coalition members can act on locally."}'
node scripts/insert-event-draft.mjs '{"title":"Global Off-Grid Solar Forum & Expo 2026","start_date":"2026-10-27","time":"27–29 Oct 2026","location":"Kigali Convention Centre, Kigali, Rwanda","mode":"In person","org":"GOGLA & World Bank ESMAP","link":"https://www.offgridsolarforum.org/","description":"East Africa largest distributed-energy gathering — solar home systems, mini-grids and clean energy access across the continent."}'
node scripts/insert-event-draft.mjs '{"title":"5th EIK International Environmental Conference & Expo 2026","start_date":"2026-10-28","time":"28–30 Oct 2026","location":"Mombasa, Kenya","mode":"In person","org":"Environment Institute of Kenya (EIK)","link":"https://conference.eik.co.ke/","description":"Theme Climate Financing Frontiers 2026 — Kenya flagship environmental-professionals conference on unlocking capital for a climate-resilient future."}'
node scripts/insert-event-draft.mjs '{"title":"COP31 — 31st UNFCCC Conference of the Parties","start_date":"2026-11-09","time":"9–20 Nov 2026","location":"Antalya, Türkiye","mode":"Hybrid","org":"UNFCCC / COP31 Presidency","link":"https://unfccc.int/cop31","description":"Central annual UN climate negotiations — finance, adaptation, loss & damage and just transition outcomes defining the African climate-justice agenda."}'
node scripts/insert-event-draft.mjs '{"title":"2nd Annual ESG and Climate Africa Summit 2026","start_date":"2026-11-24","time":"24–25 Nov 2026","location":"Nairobi, Kenya","mode":"In person","org":"Leadvent Group","link":"https://www.leadventgrp.com/events/2nd-annual-esg-and-climate-africa-summit/details","description":"Nairobi summit on ESG integration and climate action across Africa — executives, policymakers and investors on sustainable, responsible business."}'

echo "Queued 9 event drafts — awaiting admin review."
