#!/usr/bin/env bash
# Weekly MazingiraKenya Narrative-Disinfo queue — 2026-09-22
# Queues UNPUBLISHED drafts (published=false) into Supabase disinfo_items for admin review.
# The device shell cannot reach Supabase directly; this run wrote the drafts via a connected
# Chrome (POST /rest/v1/disinfo_items with the public anon key, 201). This script reproduces the
# same inserts anywhere Supabase IS reachable, via scripts/insert-disinfo-draft.mjs.
#   Usage: bash scripts/queue-disinfo-2026-09-22.sh
set -euo pipefail
cd "$(dirname "$0")/.."

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on social media", "body": "Atmospheric CO₂ was only about 345 ppm in 2025 — nowhere near the alarming levels climate scientists keep claiming.", "verdict": "Climate denial / data manipulation", "verdict_class": "vf", "source_url": "https://pesacheck.org/false-atmospheric-carbon-dioxide-was-not-345ppm-in-2025/", "source_label": "PesaCheck · CO₂ '\''345 ppm'\'' fact-check", "rebuttal": "Every credible monitoring source puts 2025 CO₂ at roughly 420–430 ppm, not 345 ppm. Measured directly at the Mauna Loa / Scripps observatory, it rose from about 425 ppm to about 430 ppm across the year. The last time CO₂ was near 345 ppm was the early 1980s. Over the past 800,000 years it never rose above ~300 ppm until the 1960s, so today'\''s level is unprecedented in that record and is driven by fossil-fuel burning. Quoting a decades-old number as if it were current simply understates how far CO₂ has climbed."}'

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on social media", "body": "A new Little Ice Age has already begun — we'\''re heading into 30 cold years, so global warming is over.", "verdict": "Climate denial (cooling myth)", "verdict_class": "vf", "source_url": "https://pesacheck.org/false-a-little-ice-age-has-not-begun/", "source_label": "PesaCheck · '\''Little Ice Age'\'' fact-check", "rebuttal": "There is no Little Ice Age underway. The historical Little Ice Age (roughly 1300–1850) was a modest ~0.6°C average cooling driven by natural factors such as volcanic activity and weak solar output. Today the planet is warming, not cooling: the most recent years are the hottest on instrumental record. The slow orbital cycles that trigger genuine ice ages act over tens of thousands of years, and human-caused warming is now strong enough that it may actually delay the next glacial period. A forecast of '\''30 cold years'\'' contradicts every observed temperature trend."}'

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on X", "body": "Glaciers are suddenly surging and growing again — proof that climate change is a scam.", "verdict": "Cherry-picking / denial", "verdict_class": "vf", "source_url": "https://pesacheck.org/false-surging-glaciers-do-not-mean-climate-change-is-a-scam/", "source_label": "PesaCheck · surging-glaciers fact-check", "rebuttal": "A '\''surging'\'' glacier is a rare, well-understood special type — under 1% of the world'\''s glaciers — that stays dormant then briefly flows much faster for internal reasons unrelated to short-term climate; warming can even make a glacier look '\''longer'\'' while its ice is actually thinning. Such surges say nothing about the global picture, which is unambiguous: glaciers worldwide have lost mass for decades and the loss is accelerating. In East Africa the ice on Mt Kenya, Kilimanjaro and the Rwenzori is nearly gone and is expected to vanish within decades. Using the rare exception to dismiss the overwhelming trend is textbook cherry-picking."}'

node scripts/insert-disinfo-draft.mjs '{"name": "Circulating on social media", "body": "It'\''s crazy to claim climate change reduces crop yields — extra CO₂ just makes the planet greener and boosts harvests.", "verdict": "Misleading (CO₂-is-good framing)", "verdict_class": "vm", "source_url": "https://pesacheck.org/fact-checked-does-climate-change-reduce-crop-yields/", "source_label": "PesaCheck · climate & crop-yields fact-check", "rebuttal": "CO₂ does aid photosynthesis, and some regions have greened — but that does not make climate change harmless for food. Evidence shows warming is already cutting yields of major staples in many places through heat stress, drought, disrupted rainfall, pests and disease, with effects varying by crop and location. For East Africa, where farming is largely rain-fed, hotter growing seasons and more erratic rains threaten maize and other staples far more than any CO₂ '\''fertilisation'\'' benefit helps. '\''The planet looks greener'\'' is not the same as '\''harvests are safe.'\''"}'

echo "Queued 4 disinfo drafts (2026-09-22) — awaiting admin review."
